spring:
  threads:
    virtual:
      enabled: true
server:
  port: 8080
unblu:
  host: ${UNBLU_HOST}
  user: ${UNBLU_USER}
  password: ${UNBLU_PASSWORD}
  middleware:
    url: ${MIDDLEWARE_URL}
    name: Test middleware
    auto-register: true
  outbound-requests:
    secret: ${BOT_SECRET}
  bot:
    onboardingFilter: VISITORS
    person:
      sourceId: concierge-bot-person-id
      first-name: Unblu
      last-name: Concierge
    clean-previous: true
    retry-count: 0
    retry-delay-in-milli-seconds: 5000
  webhook:
    secret: ${WEBHOOK_SECRET}
    clean-previous: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
